[build]
builder = "railpack"

[deploy]
startCommand = "python manage.py migrate && gunicorn A_express.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
