[build]
builder = "railpack"

[deploy]
startCommand = "python manage.py collectstatic --noinput && bash migrate_production.sh && python manage.py create_superuser_from_env && daphne -b 0.0.0.0 -p $PORT A_express.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
