[build]
builder = "railpack"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_superuser_from_env && gunicorn A_express.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
